### ISSUE TITLE
Shifting problem 

### ISSUE THREAD

**Issue by JanH75** [LukasL28/arduino_gear_shifter#9]
Problem during shifting from 1 to 2, 3 to 4.
MB3 doesen‘t turn off. It‘s needed to be turned off because the zylinder can‘t go to mid position. It has to turned MB1 and then MB3 for mid position.

**Comment by LukasL28** [comment]
Hier kannst du auf Deutsch schreiben :D das ist keine Code Dokumentation. Hast du das Kupplungs Relais richtig angeschlossen, denn laut Code müsste es während des schaltvoegangs aktiv sein

**Comment by JanH75** [comment]
Ja sag das doch ._.
ja Kupplung ist aktiv. Problem ist nur das der Zylinder wenn er in der vorherigen Stellung ausgefahren ist nicht in die mittelstellung fährt.
Das liegt daran das MB3 nicht ausschaltet.
